const {
  registerUser,
  checkIdByEmailOrUserName,
  getUserDataById,
  deleteUser,
  getAllUserData,
  updateUserData,
} = require('./users');
const {
  createProcessorProduction,
  connectProcessorUser,
  getProcessorConnectionByUserId,
  deleteProcessorConnectionData,
  getProcessorByProcessorId,
} = require('./processor');
const {
  createControllerProduction,
  connectControllerProcessor,
  updateUserControllerData,
  deleteControllerConnection,
  getControllerByControllerId,
  addControllerType,
  getControllerTypeByLabel,
  getControllerType,
  updateControllerType,
  deleteControllerType,
  addControllerLocation,
  getControllerLocation,
  updateControllerLocation,
  deleteControllerLocation,
} = require('./controller');

module.exports = {
  registerUser,
  checkIdByEmailOrUserName,
  getUserDataById,
  deleteUser,
  getAllUserData,
  updateUserData,
  createProcessorProduction,
  connectProcessorUser,
  getProcessorConnectionByUserId,
  deleteProcessorConnectionData,
  createControllerProduction,
  connectControllerProcessor,
  getProcessorByProcessorId,
  updateUserControllerData,
  deleteControllerConnection,
  getControllerByControllerId,
  addControllerType,
  getControllerTypeByLabel,
  getControllerType,
  updateControllerType,
  deleteControllerType,
  addControllerLocation,
  getControllerLocation,
  updateControllerLocation,
  deleteControllerLocation,
};
