const {
  registerUser,
  checkIdByEmailOrUserName,
  getUserDataById,
  deleteUser,
  getAllUsersForAdmin,
  getAllUserData,
  updateUserData,
} = require('./users');
const {
  createProcessorProduction,
  connectProcessorUser,
  getProcessorConnectionByUserId,
  deleteProcessorConnectionData,
  getProcessorByProcessorId,
  getProcessorByConnectionId,
  getAllProcessorProductionForAdmin
} = require('./processor');
const {
  createControllerProduction,
  getAllControllerProductionForAdmin,
  connectControllerProcessor,
  updateUserControllerData,
  deleteControllerConnection,
  getControllerByControllerId,
  changeControllerStatus,
  getControllerByProcessorId,
  getControllerByUserId,
  addControllerType,
  getControllerTypeByLabel,
  getControllerType,
  updateControllerType,
  deleteControllerType,
  getAllControllerType,
  addControllerLocation,
  getControllerLocation,
  updateControllerLocation,
  deleteControllerLocation,
  getAllControllerLocation,
  getControllerLocationByLabel,
} = require('./controller');

module.exports = {
  registerUser,
  checkIdByEmailOrUserName,
  getUserDataById,
  deleteUser,
  getAllUsersForAdmin,
  getAllUserData,
  updateUserData,
  createProcessorProduction,
  connectProcessorUser,
  getProcessorConnectionByUserId,
  deleteProcessorConnectionData,
  createControllerProduction,
  getAllControllerProductionForAdmin,
  connectControllerProcessor,
  getProcessorByProcessorId,
  getProcessorByConnectionId,getAllProcessorProductionForAdmin,
  updateUserControllerData,
  deleteControllerConnection,
  getControllerByControllerId,
  changeControllerStatus,
  getControllerByProcessorId,
  getControllerByUserId,
  addControllerType,
  getControllerTypeByLabel,
  getControllerType,
  updateControllerType,
  deleteControllerType,
  getAllControllerType,
  addControllerLocation,
  getControllerLocation,
  updateControllerLocation,
  deleteControllerLocation,
  getAllControllerLocation,
  getControllerLocationByLabel,
};
